// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MiniProgramLoginRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiniProgramLoginRequest) Reset()         { *m = MiniProgramLoginRequest{} }
func (m *MiniProgramLoginRequest) String() string { return proto.CompactTextString(m) }
func (*MiniProgramLoginRequest) ProtoMessage()    {}
func (*MiniProgramLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *MiniProgramLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiniProgramLoginRequest.Unmarshal(m, b)
}
func (m *MiniProgramLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiniProgramLoginRequest.Marshal(b, m, deterministic)
}
func (m *MiniProgramLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniProgramLoginRequest.Merge(m, src)
}
func (m *MiniProgramLoginRequest) XXX_Size() int {
	return xxx_messageInfo_MiniProgramLoginRequest.Size(m)
}
func (m *MiniProgramLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniProgramLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MiniProgramLoginRequest proto.InternalMessageInfo

func (m *MiniProgramLoginRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *MiniProgramLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PhoneCodeLoginRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneCodeLoginRequest) Reset()         { *m = PhoneCodeLoginRequest{} }
func (m *PhoneCodeLoginRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneCodeLoginRequest) ProtoMessage()    {}
func (*PhoneCodeLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *PhoneCodeLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneCodeLoginRequest.Unmarshal(m, b)
}
func (m *PhoneCodeLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneCodeLoginRequest.Marshal(b, m, deterministic)
}
func (m *PhoneCodeLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneCodeLoginRequest.Merge(m, src)
}
func (m *PhoneCodeLoginRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneCodeLoginRequest.Size(m)
}
func (m *PhoneCodeLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneCodeLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneCodeLoginRequest proto.InternalMessageInfo

func (m *PhoneCodeLoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PhoneCodeLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type EmailCodeLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailCodeLoginRequest) Reset()         { *m = EmailCodeLoginRequest{} }
func (m *EmailCodeLoginRequest) String() string { return proto.CompactTextString(m) }
func (*EmailCodeLoginRequest) ProtoMessage()    {}
func (*EmailCodeLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *EmailCodeLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailCodeLoginRequest.Unmarshal(m, b)
}
func (m *EmailCodeLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailCodeLoginRequest.Marshal(b, m, deterministic)
}
func (m *EmailCodeLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailCodeLoginRequest.Merge(m, src)
}
func (m *EmailCodeLoginRequest) XXX_Size() int {
	return xxx_messageInfo_EmailCodeLoginRequest.Size(m)
}
func (m *EmailCodeLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailCodeLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailCodeLoginRequest proto.InternalMessageInfo

func (m *EmailCodeLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailCodeLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PasswordLoginRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordLoginRequest) Reset()         { *m = PasswordLoginRequest{} }
func (m *PasswordLoginRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordLoginRequest) ProtoMessage()    {}
func (*PasswordLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *PasswordLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordLoginRequest.Unmarshal(m, b)
}
func (m *PasswordLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordLoginRequest.Marshal(b, m, deterministic)
}
func (m *PasswordLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordLoginRequest.Merge(m, src)
}
func (m *PasswordLoginRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordLoginRequest.Size(m)
}
func (m *PasswordLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordLoginRequest proto.InternalMessageInfo

func (m *PasswordLoginRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PasswordLoginRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *PasswordLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*MiniProgramLoginRequest)(nil), "MiniProgramLoginRequest")
	proto.RegisterType((*PhoneCodeLoginRequest)(nil), "PhoneCodeLoginRequest")
	proto.RegisterType((*EmailCodeLoginRequest)(nil), "EmailCodeLoginRequest")
	proto.RegisterType((*PasswordLoginRequest)(nil), "PasswordLoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0x5a, 0xb5, 0x23, 0x16, 0x19, 0xda, 0xba, 0x14, 0x0f, 0x12, 0x10, 0x3c, 0xed,
	0x41, 0x6f, 0x82, 0x82, 0x88, 0x78, 0x51, 0x09, 0x7d, 0x83, 0xb5, 0x19, 0xda, 0x68, 0xb2, 0x13,
	0xb3, 0x11, 0xdf, 0x5e, 0x24, 0x63, 0xa2, 0xac, 0x6e, 0xa0, 0xb7, 0xfc, 0xfb, 0x33, 0xdf, 0x4e,
	0x3e, 0x16, 0xf6, 0x73, 0x5e, 0x66, 0x56, 0x97, 0x15, 0xd7, 0x1c, 0xdf, 0xc3, 0xd1, 0x63, 0x66,
	0xb3, 0xa4, 0xe2, 0x65, 0x65, 0x8a, 0x87, 0xa6, 0x99, 0xd3, 0xdb, 0x3b, 0xb9, 0x1a, 0x15, 0xec,
	0x2e, 0x56, 0xc6, 0x5a, 0xca, 0x55, 0x74, 0x12, 0x9d, 0x0d, 0xe7, 0x5d, 0x44, 0x84, 0xed, 0x05,
	0xa7, 0xa4, 0x36, 0xe5, 0x58, 0xbe, 0xe3, 0x1b, 0x98, 0x24, 0x2b, 0xb6, 0x74, 0xcb, 0x29, 0x79,
	0x98, 0x31, 0x0c, 0xca, 0xa6, 0x68, 0x21, 0xdf, 0xa1, 0x0f, 0x71, 0x57, 0x98, 0x2c, 0x0f, 0x21,
	0xa8, 0x29, 0x3a, 0x84, 0x84, 0x20, 0xe2, 0x05, 0xc6, 0x89, 0x71, 0xee, 0x83, 0xab, 0x74, 0xcd,
	0x7f, 0x39, 0x86, 0xa1, 0xf8, 0x78, 0x32, 0x45, 0x87, 0xfa, 0x3d, 0xc0, 0x19, 0xec, 0x95, 0x2d,
	0x4f, 0x6d, 0x49, 0xf9, 0x93, 0xe3, 0x53, 0x38, 0x68, 0xef, 0x70, 0x25, 0x5b, 0x47, 0xcd, 0x9a,
	0x35, 0xbf, 0x92, 0xed, 0xd6, 0x94, 0x70, 0xfe, 0x19, 0xc1, 0x40, 0x80, 0x78, 0x0d, 0x87, 0x7f,
	0x5d, 0xa3, 0xd2, 0x3d, 0xfa, 0x67, 0x23, 0xed, 0xd1, 0xe3, 0x0d, 0xbc, 0x84, 0x91, 0xaf, 0x18,
	0xa7, 0x3a, 0xe8, 0x3c, 0x3c, 0xeb, 0xbb, 0xc5, 0xa9, 0x0e, 0xca, 0x0e, 0xcc, 0x5e, 0x01, 0xca,
	0x35, 0x9e, 0x59, 0x9c, 0xe8, 0x90, 0xe9, 0xff, 0xe3, 0xcf, 0x3b, 0xf2, 0xd2, 0x2e, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x29, 0xeb, 0x65, 0x4b, 0x78, 0x02, 0x00, 0x00,
}
