---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: vet
    image: golang:latest
    commands:
      - go vet -v ./...
    volumes:
      - name: gopath
        path: /go

  - name: test
    image: golang:latest
    commands:
      - go test -v ./...
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

---
kind: pipeline
type: docker
name: login-srv

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build -v -o login-srv srv\login-srv\main.go
    volumes:
      - name: gopath
        path: /go

  - name: run
    image: golang:latest
    commands:
      - login-srv --help
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}
