---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: vet
    image: golang:latest
    commands:
      - go vet -v ./...
    volumes:
      - name: gopath
        path: /go

  - name: lint
    image: golang:latest
    commands:
      - go get -u github.com/mgechev/revive
      - revive -config .revive.toml ./... || exit 1
    volumes:
      - name: gopath
        path: /go

  - name: test
    image: golang:latest
    commands:
      - go test -v ./...
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

---
kind: pipeline
type: docker
name: hello-srv

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build -v -o hello-srv -ldflags "-s -w" srv/hello-srv/main.go
    volumes:
      - name: gopath
        path: /go

  - name : upx
    image: cnbattle/drone-upx
    settings:
      level: 9
      save_file: ./hello-srv-upx
      original_file: ./hello-srv
    volumes:
      - name: gopath
        path: /go

  - name: run
    image: golang:latest
    commands:
      - ./hello-srv-upx --help
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

depends_on:
  - testing

---
kind: pipeline
type: docker
name: login-srv

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build -v -o login-srv -ldflags "-s -w" srv/login-srv/main.go
    volumes:
      - name: gopath
        path: /go

  - name : upx
    image: cnbattle/drone-upx
    settings:
      level: 9
      save_file: ./login-srv-upx
      original_file: ./login-srv
    volumes:
      - name: gopath
        path: /go


  - name: run
    image: golang:latest
    commands:
      - ./login-srv-upx --help
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

depends_on:
  - testing

---
kind: pipeline
type: docker
name: user-srv

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build -v -o user-srv -ldflags "-s -w" srv/user-srv/main.go
    volumes:
      - name: gopath
        path: /go

  - name : upx
    image: cnbattle/drone-upx
    settings:
      level: 9
      save_file: ./user-srv-upx
      original_file: ./user-srv
    volumes:
      - name: gopath
        path: /go

  - name: run
    image: golang:latest
    commands:
      - ./user-srv-upx --help
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

depends_on:
  - testing

---
kind: pipeline
type: docker
name: article-srv

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build -v -o article-srv -ldflags "-s -w" srv/article-srv/main.go
    volumes:
      - name: gopath
        path: /go

  - name : upx
    image: cnbattle/drone-upx
    settings:
      level: 9
      save_file: ./article-srv-upx
      original_file: ./article-srv
    volumes:
      - name: gopath
        path: /go

  - name: run
    image: golang:latest
    commands:
      - ./article-srv-upx --help
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

depends_on:
  - testing

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_user_id

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**

depends_on:
  - hello-srv
  - login-srv
  - user-srv
  - article-srv