// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: article.proto

package article

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Article service

type ArticleService interface {
	Detail(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type articleService struct {
	c    client.Client
	name string
}

func NewArticleService(name string, c client.Client) ArticleService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "article"
	}
	return &articleService{
		c:    c,
		name: name,
	}
}

func (c *articleService) Detail(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Article.Detail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Article service

type ArticleHandler interface {
	Detail(context.Context, *Request, *Response) error
}

func RegisterArticleHandler(s server.Server, hdlr ArticleHandler, opts ...server.HandlerOption) error {
	type article interface {
		Detail(ctx context.Context, in *Request, out *Response) error
	}
	type Article struct {
		article
	}
	h := &articleHandler{hdlr}
	return s.Handle(s.NewHandler(&Article{h}, opts...))
}

type articleHandler struct {
	ArticleHandler
}

func (h *articleHandler) Detail(ctx context.Context, in *Request, out *Response) error {
	return h.ArticleHandler.Detail(ctx, in, out)
}
