// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type LoginRequest struct {
	IdentityType         string   `protobuf:"bytes,1,opt,name=identityType,proto3" json:"identityType,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	AutoRegister         bool     `protobuf:"varint,3,opt,name=autoRegister,proto3" json:"autoRegister,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *LoginRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *LoginRequest) GetAutoRegister() bool {
	if m != nil {
		return m.AutoRegister
	}
	return false
}

type BaseRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (m *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(m, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type AuthResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IdentityType         string   `protobuf:"bytes,2,opt,name=identityType,proto3" json:"identityType,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Certificate          string   `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AuthResponse) GetIdentityType() string {
	if m != nil {
		return m.IdentityType
	}
	return ""
}

func (m *AuthResponse) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *AuthResponse) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

type BaseResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *BaseResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *BaseResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *BaseResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *BaseResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*BaseRequest)(nil), "BaseRequest")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
	proto.RegisterType((*BaseResponse)(nil), "BaseResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0x27, 0xf3, 0x8f, 0x99, 0x3b, 0x1d, 0xf8, 0xc8, 0xe2, 0xa3, 0x14, 0xc1, 0x92, 0x8d,
	0x03, 0x42, 0x17, 0xfa, 0x04, 0x8a, 0x4b, 0x57, 0xc5, 0x17, 0x88, 0xed, 0xb5, 0x06, 0x35, 0xad,
	0xc9, 0x8d, 0x30, 0x5b, 0x77, 0xfa, 0xd4, 0x92, 0x4e, 0x5b, 0x33, 0x8e, 0x83, 0xbb, 0x9e, 0x73,
	0x4f, 0xc9, 0x2f, 0x39, 0x17, 0xc0, 0x59, 0x34, 0x59, 0x63, 0x6a, 0xaa, 0xc5, 0x29, 0xac, 0xae,
	0x1c, 0x3d, 0xe6, 0xf8, 0xea, 0xd0, 0x12, 0xff, 0x07, 0x13, 0xa7, 0xca, 0x98, 0xa5, 0x6c, 0xb3,
	0xcc, 0xfd, 0xa7, 0x30, 0x10, 0xdd, 0xd6, 0x95, 0xd2, 0x7d, 0x42, 0x40, 0xa4, 0x4a, 0xd4, 0xa4,
	0x68, 0x7b, 0xb7, 0x6d, 0xb0, 0x8b, 0xee, 0x79, 0x3c, 0x81, 0x45, 0xaf, 0xe3, 0x71, 0x3b, 0x1f,
	0xb4, 0xff, 0x5f, 0x3a, 0xaa, 0x73, 0xac, 0x94, 0x25, 0x34, 0xf1, 0x24, 0x65, 0x9b, 0x45, 0xbe,
	0xe7, 0x79, 0xa8, 0x6b, 0x69, 0xf1, 0x38, 0xd4, 0x3b, 0x83, 0x68, 0x87, 0x6d, 0x9b, 0x5a, 0x5b,
	0x3c, 0x8c, 0x1c, 0x70, 0x8e, 0xff, 0xe0, 0x9c, 0xfc, 0xe0, 0x4c, 0x61, 0x55, 0xa0, 0x21, 0xf5,
	0xa0, 0x0a, 0x49, 0x18, 0x4f, 0xdb, 0x71, 0x68, 0x89, 0x4f, 0x06, 0xd1, 0x0e, 0xf3, 0x28, 0x44,
	0x02, 0x0b, 0xad, 0x8a, 0x27, 0x2d, 0x5f, 0x7a, 0x80, 0x41, 0xf3, 0xff, 0x30, 0x97, 0x6f, 0x92,
	0xa4, 0xe9, 0x8e, 0xee, 0x94, 0xf7, 0x2b, 0xd4, 0x25, 0x9a, 0xee, 0xcc, 0x4e, 0xf1, 0x13, 0x58,
	0x5a, 0x55, 0x69, 0x49, 0xce, 0x60, 0x3c, 0x6b, 0x47, 0xdf, 0xc6, 0xc5, 0x07, 0x83, 0xa9, 0xaf,
	0x95, 0x9f, 0xc1, 0xac, 0xed, 0x8b, 0xaf, 0xb3, 0xb0, 0xb7, 0x64, 0x9d, 0x85, 0x0f, 0x26, 0x46,
	0xfc, 0x1c, 0xc0, 0x3b, 0x37, 0x48, 0x52, 0x3d, 0xf3, 0x28, 0x0b, 0xd6, 0xe0, 0xd7, 0xb0, 0xbf,
	0xea, 0x10, 0x0e, 0xea, 0x49, 0xd6, 0x59, 0xf8, 0x0a, 0x62, 0x74, 0x3f, 0x6f, 0x57, 0xeb, 0xf2,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0xea, 0xf3, 0xb5, 0x6e, 0x68, 0x02, 0x00, 0x00,
}
